repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy-check
        types: [python]
        name: mypy-check
        entry: mypy src
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/python-poetry/poetry
    rev: "1.7.0"
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--no-update"]

  - repo: https://github.com/python-poetry/poetry-plugin-export
    rev: "1.7.0"
    hooks:
      - id: poetry-export
        args:
          [
            "--without-hashes",
            "-f",
            "requirements.txt",
            "-o",
            "requirements.txt",
          ]
        verbose: true
